# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locate',
            name='around',
        ),
        migrations.DeleteModel(
            name='around_locations',
        ),
    ]
