# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locate', '0002_locate_google_map_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locate',
            unique_together=set([('latitude', 'longitude')]),
        ),
    ]
